# Gradle Properties
org.gradle.jvmargs=-Xmx2G -Djava.version=21.0.2
org.gradle.parallel=true
kotlin.daemon.jvmargs=-Xmx1G -Djava.version=21.0.2

# Dependencies
minecraft_version=26.2
quilt_mappings=1
quilt_loader_version=0.30.1
quilt_kotlin_version=5.0.0+kt.2.0.21+flk.1.12.3
detekt_version=1.23.8
kotest_version=6.2.4
